# Generated by Django 5.2.6 on 2025-09-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Nombre legal o comercial de la empresa.', max_length=150, unique=True, verbose_name='Razón Social')),
                ('cuit', models.CharField(help_text='Número de Identificación Fiscal. Máximo 11 dígitos.', max_length=11, unique=True, verbose_name='CUIT')),
                ('es_proveedor', models.BooleanField(default=False, help_text='Marca si esta empresa actúa como proveedor de pallets/servicios.', verbose_name='¿Es Proveedor?')),
                ('condicion_iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MT', 'Monotributo'), ('EX', 'Exento'), ('CF', 'Consumidor Final')], default='CF', max_length=2, verbose_name='Condición ante el IVA')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección Principal')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
