# Generated by Django 4.2.25 on 2025-10-21 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(error_messages={'blank': 'La razón social es obligatoria.', 'max_length': 'La razón social no puede exceder los 150 caracteres.', 'unique': 'Ya existe una empresa con esta razón social.'}, help_text='Nombre legal o comercial de la empresa.', max_length=150, unique=True, verbose_name='Razón Social')),
                ('cuit', models.CharField(error_messages={'blank': 'El CUIT es obligatorio.', 'max_length': 'El CUIT no puede exceder los 11 caracteres.', 'unique': 'Ya existe una empresa con este CUIT.'}, help_text='Número de Identificación Fiscal. Máximo 11 dígitos.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cuit', message='El CUIT debe tener exactamente 11 dígitos numéricos.', regex='^\\d{11}$')], verbose_name='CUIT')),
                ('es_proveedor', models.BooleanField(default=False, help_text='Marca si esta empresa actúa como proveedor de pallets/servicios.', verbose_name='¿Es Proveedor?')),
                ('condicion_iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MT', 'Monotributo'), ('EX', 'Exento'), ('CF', 'Consumidor Final')], default='CF', error_messages={'blank': 'La condición de IVA es obligatoria.'}, max_length=2, verbose_name='Condición ante el IVA')),
                ('direccion', models.CharField(error_messages={'blank': 'La dirección es obligatoria.', 'max_length': 'La dirección no puede exceder los 255 caracteres.'}, max_length=255, verbose_name='Dirección Principal')),
                ('email', models.EmailField(blank=True, error_messages={'invalid': 'Ingrese un correo electrónico válido.', 'max_length': 'El correo electrónico no puede exceder los 100 caracteres.'}, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_telefono', message='El teléfono debe tener entre 7 y 20 caracteres y contener solo dígitos, espacios, guiones, paréntesis y signo más.', regex='^[\\d\\-\\+\\(\\)\\s]{7,20}$')], verbose_name='Teléfono')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
