# Generated by Django 4.2.25 on 2025-10-18 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='condicion_iva',
            field=models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MT', 'Monotributo'), ('EX', 'Exento'), ('CF', 'Consumidor Final')], default='CF', error_messages={'blank': 'La condición de IVA es obligatoria.'}, max_length=2, verbose_name='Condición ante el IVA'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(error_messages={'blank': 'El CUIT es obligatorio.', 'max_length': 'El CUIT no puede exceder los 11 caracteres.', 'unique': 'Ya existe una empresa con este CUIT.'}, help_text='Número de Identificación Fiscal. Máximo 11 dígitos.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cuit', message='El CUIT debe tener exactamente 11 dígitos numéricos.', regex='^\\d{11}$')], verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(error_messages={'blank': 'La dirección es obligatoria.', 'max_length': 'La dirección no puede exceder los 255 caracteres.'}, max_length=255, verbose_name='Dirección Principal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'Ingrese un correo electrónico válido.', 'max_length': 'El correo electrónico no puede exceder los 100 caracteres.'}, max_length=100, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(error_messages={'blank': 'La razón social es obligatoria.', 'max_length': 'La razón social no puede exceder los 150 caracteres.', 'unique': 'Ya existe una empresa con esta razón social.'}, help_text='Nombre legal o comercial de la empresa.', max_length=150, unique=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_telefono', message='El teléfono debe tener entre 7 y 20 caracteres y contener solo dígitos, espacios, guiones, paréntesis y signo más.', regex='^[\\d\\-\\+\\(\\)\\s]{7,20}$')], verbose_name='Teléfono'),
        ),
    ]
