# Generated by Django 4.2.25 on 2025-10-18 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='alto_mm',
            field=models.PositiveIntegerField(error_messages={'invalid': 'El alto debe ser un número positivo.'}, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Alto (mm)'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='ancho_mm',
            field=models.PositiveIntegerField(error_messages={'invalid': 'El ancho debe ser un número positivo.'}, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ancho (mm)'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='calidad',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', error_messages={'blank': 'La calidad es obligatoria.'}, max_length=1),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='codigo',
            field=models.CharField(error_messages={'blank': 'El código es obligatorio.', 'unique': 'Ya existe un pallet con este código.'}, help_text='Identificador único del pallet (etiqueta/QR).', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('EN_REPARACION', 'En reparación'), ('BAJA', 'Baja')], default='DISPONIBLE', error_messages={'blank': 'El estado es obligatorio.'}, max_length=15),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='largo_mm',
            field=models.PositiveIntegerField(error_messages={'invalid': 'El largo debe ser un número positivo.'}, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Largo (mm)'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='material',
            field=models.CharField(choices=[('MADERA', 'Madera'), ('PLASTICO', 'Plástico'), ('METAL', 'Metal')], error_messages={'blank': 'El material es obligatorio.'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='peso_max_kg',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Ingrese un peso válido.'}, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Peso máx. admitido (kg)'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='vida_util_meses',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vida útil (meses)'),
        ),
    ]
