# Generated by Django 5.2.6 on 2025-09-25 01:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('tipo', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], max_length=5, verbose_name='Tipo de Movimiento')),
                ('ubicacion_origen', models.CharField(help_text='Galpón propio o dirección de la empresa de origen.', max_length=255, verbose_name='Ubicación de Origen')),
                ('ubicacion_destino', models.CharField(help_text='Galpón propio o dirección de la empresa a donde llega el pallet.', max_length=255, verbose_name='Ubicación de Destino')),
                ('doc_referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Remito / Documento')),
                ('estado_confirmacion', models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10, verbose_name='Estado de Confirmación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='empresas.empresa', verbose_name='Empresa Asociada')),
                ('usuario_creacion', models.ForeignKey(help_text='Usuario que registró el movimiento en el sistema.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
            options={
                'verbose_name': 'Movimiento (Cabecera)',
                'verbose_name_plural': 'Movimientos (Cabeceras)',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='LineaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pallet', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='Tipo de Pallet (Calidad)')),
                ('cantidad', models.PositiveIntegerField(help_text='La cantidad de pallets de este tipo en la transacción.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('motivo', models.CharField(help_text='(Entrega, Devolución, Reparación, etc.)', max_length=100, verbose_name='Motivo')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='movimientos.movimiento', verbose_name='Movimiento Asociado')),
            ],
            options={
                'verbose_name': 'Línea de Movimiento (Detalle)',
                'verbose_name_plural': 'Líneas de Movimiento (Detalles)',
            },
        ),
    ]
