# Generated by Django 4.2.25 on 2025-10-18 20:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_condicion_iva_alter_empresa_cuit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineamovimiento',
            name='cantidad',
            field=models.PositiveIntegerField(error_messages={'invalid': 'La cantidad debe ser un número positivo.'}, help_text='La cantidad de pallets de este tipo en la transacción.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='lineamovimiento',
            name='motivo',
            field=models.CharField(error_messages={'blank': 'El motivo es obligatorio.', 'max_length': 'El motivo no puede exceder los 100 caracteres.'}, help_text='(Entrega, Devolución, Reparación, etc.)', max_length=100, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='lineamovimiento',
            name='movimiento',
            field=models.ForeignKey(error_messages={'null': 'El movimiento asociado es obligatorio.'}, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='movimientos.movimiento', verbose_name='Movimiento Asociado'),
        ),
        migrations.AlterField(
            model_name='lineamovimiento',
            name='tipo_pallet',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], error_messages={'blank': 'El tipo de pallet es obligatorio.'}, max_length=1, verbose_name='Tipo de Pallet (Calidad)'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='doc_referencia',
            field=models.CharField(blank=True, error_messages={'max_length': 'El documento de referencia no puede exceder los 50 caracteres.'}, max_length=50, null=True, verbose_name='Número de Remito / Documento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='empresa',
            field=models.ForeignKey(error_messages={'null': 'La empresa es obligatoria.'}, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='empresas.empresa', verbose_name='Empresa Asociada'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='estado_confirmacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', error_messages={'blank': 'El estado de confirmación es obligatorio.'}, max_length=10, verbose_name='Estado de Confirmación'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], error_messages={'blank': 'El tipo de movimiento es obligatorio.'}, max_length=5, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='ubicacion_destino',
            field=models.CharField(error_messages={'blank': 'La ubicación de destino es obligatoria.', 'max_length': 'La ubicación de destino no puede exceder los 255 caracteres.'}, help_text='Galpón propio o dirección de la empresa a donde llega el pallet.', max_length=255, verbose_name='Ubicación de Destino'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='ubicacion_origen',
            field=models.CharField(error_messages={'blank': 'La ubicación de origen es obligatoria.', 'max_length': 'La ubicación de origen no puede exceder los 255 caracteres.'}, help_text='Galpón propio o dirección de la empresa de origen.', max_length=255, verbose_name='Ubicación de Origen'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='usuario_creacion',
            field=models.ForeignKey(error_messages={'null': 'El usuario creador es obligatorio.'}, help_text='Usuario que registró el movimiento en el sistema.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
    ]
